In [1]:
#Executing stack
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
#Executing hstack
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [13]:
#Executing split
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 50)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype

In [15]:
#Executing split for 2D Array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = np.array_split(arr, 2)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [19]:
#Executing hsplit
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [21]:
#Executing where for searching
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [25]:
#Using sort
import numpy as np

arr = np.array([1, 4, 5, 3, 7, 1])
newarr = np.sort(arr)
print(newarr)

[1 1 3 4 5 7]


In [35]:
#Trying matrix
import numpy as np
from numpy import linalg as LA

A = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])

#Rank
print("Rank of A: ", LA.matrix_rank(A))

#Trace
print("\nTrace of A: ", np.trace(A))

#Determinant
print("\nDeterminant of A: ", LA.det(A))

#Inverse
print("\nInverse of A:\n", LA.inv(A))

#Raise to power
print("\nMatrix A raised to power 3: \n", LA.matrix_power(A, 3))

Rank of A:  3

Trace of A:  11

Determinant of A:  -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3: 
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [2]:
#Obtaining the eigen value and vector
import numpy as np
from numpy import linalg as LA

A = np.array([[1, 2, 3], [3, 2, 1], [1, 0, -1]])
w, v = LA.eig(A)
print(w)
print(v)

[ 4.31662479e+00 -2.31662479e+00  2.13869201e-17]
[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]
